discord:
  token: ${DISCORD_BOT_TOKEN}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discord_bot
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true